#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);


#--------------------------------------------------
# actions for nethserver-wordpress-update event
#--------------------------------------------------

my $event = "nethserver-wordpress-update";

event_actions($event, 
             'initialize-default-databases' => '00',
             'nethserver-wordpress-conf' => '20',
             'nethserver-wordpress_permissions-conf' => '30'
);
templates2events("/etc/httpd/conf.d/wordpress.conf",  $event);
templates2events("/etc/httpd/conf.d/zzz_wordpress.conf",  $event);
templates2events("/etc/wordpress/wp-config.php",  $event);
templates2events("/etc/httpd/conf.d/default-virtualhost.inc", $event);
templates2events("/etc/opt/rh/rh-php72/php-fpm.d/z_wordpress.conf", $event);
event_services($event, 'httpd' => 'reload');
event_services($event, 'rh-php72-php-fpm' => 'restart');

my $event = 'trusted-networks-modify';
templates2events("/etc/httpd/conf.d/wordpress.conf",  $event);
event_services($event, 'httpd' => 'reload');
