#!/usr/bin/perl
#Added to restore good ownership on folders & script to allow 
# - Languages choices at installation
# - Ability to install Plugins & Themes directly from the admin backend

system('chown apache:apache -R /usr/share/wordpress/wp-admin/');
system('chown apache:ftp -R /usr/share/wordpress/wp-content/');


exit;
